from flask import Flask, render_template, request
import torch
import torch.nn as nn
import librosa
import librosa.display
import numpy as np
import matplotlib.pyplot as plt
import os
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

app = Flask(__name__)

SAMPLE_RATE = 4000
MAX_LEN = 400

label_map = {
    0: "ASD (Atrial Septal Defect)",
    1: "VSD (Ventricular Septal Defect)",
    2: "TOF (Tetralogy of Fallot)",
    3: "Normal Heart"
}

# ---------------------------
# HEART TRANSFORMER MODEL
# ---------------------------

class HeartTransformer(nn.Module):

    def __init__(self, input_dim=64, num_classes=4):

        super().__init__()

        self.embed = nn.Linear(input_dim, 128)

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=128,
            nhead=4,
            dim_feedforward=256,
            dropout=0.1,
            batch_first=True
        )

        self.transformer = nn.TransformerEncoder(
            encoder_layer,
            num_layers=3
        )

        self.classifier = nn.Linear(128, num_classes)

    def forward(self, x):

        x = self.embed(x)
        x = self.transformer(x)
        x = x.mean(dim=1)

        return self.classifier(x)

# ---------------------------
# LOAD MODEL
# ---------------------------

model = HeartTransformer()

model.load_state_dict(
    torch.load("heart_transformer_model.pth", map_location="cpu")
)

model.eval()

# ---------------------------
# FEATURE EXTRACTION
# ---------------------------

def extract_features(audio):

    signal, _ = librosa.load(audio, sr=SAMPLE_RATE)

    mel = librosa.feature.melspectrogram(
        y=signal,
        sr=SAMPLE_RATE,
        n_mels=64,
        n_fft=1024,
        hop_length=256
    )

    mel = librosa.power_to_db(mel)
    mel = mel.T

    if mel.shape[0] < MAX_LEN:

        pad = MAX_LEN - mel.shape[0]
        mel = np.pad(mel, ((0, pad), (0, 0)))

    else:

        mel = mel[:MAX_LEN, :]

    mel = torch.tensor(mel, dtype=torch.float32).unsqueeze(0)

    return mel

# ---------------------------
# GENERATE GRAPHS
# ---------------------------

def generate_plots(audio):

    signal, sr = librosa.load(audio, sr=SAMPLE_RATE)

    # Waveform
    plt.figure(figsize=(10,3))
    plt.plot(signal)
    plt.title("Heart Sound Waveform")
    plt.tight_layout()
    plt.savefig("static/waveform.png")
    plt.close()

def generate_report(result, confidence):

    report_path = "static/report.pdf"

    c = canvas.Canvas(report_path, pagesize=letter)

    c.setFont("Helvetica", 16)
    c.drawString(150, 750, "AI Heart Murmur Diagnostic Report")

    c.setFont("Helvetica", 12)

    c.drawString(100, 700, f"Diagnosis: {result}")
    c.drawString(100, 670, f"Confidence: {confidence}%")

    c.drawString(100, 640, "Generated by  Heart Sound Analysis System")

    c.save()

    return report_path
    # Spectrogram
    mel = librosa.feature.melspectrogram(
        y=signal,
        sr=sr,
        n_mels=64
    )

    mel_db = librosa.power_to_db(mel)

    plt.figure(figsize=(10,4))

    librosa.display.specshow(
        mel_db,
        sr=sr,
        x_axis="time",
        y_axis="mel"
    )

    plt.colorbar()
    plt.title("Mel Spectrogram")

    plt.tight_layout()

    plt.savefig("static/spectrogram.png")
    plt.close()

# ---------------------------
# FLASK ROUTE
# ---------------------------

@app.route("/", methods=["GET","POST"])
def index():

    result = None
    confidence = None

    if request.method == "POST":

        file = request.files["file"]

        path = "static/audio.wav"

        file.save(path)

        generate_plots(path)

        features = extract_features(path)

        with torch.no_grad():

            output = model(features)

            pred = torch.argmax(output, dim=1).item()

            prob = torch.softmax(output, dim=1)

            confidence = round(prob[0][pred].item()*100,2)

        result = label_map[pred]
        result = label_map[pred]

        generate_report(result, confidence)

    return render_template(
        "index.html",
        result=result,
        confidence=confidence
    )

# ---------------------------
# RUN SERVER
# ---------------------------

if __name__ == "__main__":

    app.run(debug=True)
